import os
import sys
from datetime import datetime, date, time
from sqlmodel import create_engine, Session, select, SQLModel
# Import all models
from app.models import Client, Engineer, SiteContact, Brand, ClientSite, Job, EngineerDiary, User, PasswordReset, ExtractionReport, ExtractionMicronReading, ExtractionPhoto, ExtractionInspectionItem, ExtractionFilterItem

def generate_dump():
    sqlite_url = "sqlite:///./production.sqlite"
    if not os.path.exists("production.sqlite"):
        # Fallback
        sqlite_url = "sqlite:///./pnj_database.db"
        if not os.path.exists("pnj_database.db"):
            print("Error: No database file found.")
            sys.exit(1)

    source_engine = create_engine(sqlite_url)
    
    output_file = "schema_dump.sql"
    
    # Tables in dependency order
    tables = [
        User, Client, Engineer, SiteContact, Brand, 
        ClientSite, Job, EngineerDiary, PasswordReset, 
        ExtractionReport, ExtractionMicronReading, ExtractionInspectionItem, ExtractionFilterItem, ExtractionPhoto
    ]

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("-- PNJ Cleaning Database Dump\n")
        f.write(f"-- Generated: {datetime.now()}\n\n")
        
        # 1. Schema (DDL)
        # SQLModel doesn't have a built-in "get DDL" string function nicely exposed without an engine.
        # But we can approximate the postgres DDL or just ask the user to let us handle it via the client?
        # No, the user needs to run SQL.
        # Since we are moving to REST, we don't strictly need the python app to own the schema via Alembic anymore,
        # but for this initial dump, writing the CREATE statements manually or semi-manually is safer than relying on SQLite-to-PG translation tools which can be flaky.
        # However, let's try to infer it from the models or write standard SQL.
        
        f.write("-- 1. Schema Definitions\n\n")
        
        # Users
        f.write("CREATE TABLE IF NOT EXISTS users (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    username TEXT NOT NULL UNIQUE,\n")
        f.write("    email TEXT UNIQUE,\n")
        f.write("    password TEXT NOT NULL,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")
        
        # Clients
        f.write("CREATE TABLE IF NOT EXISTS clients (\n")
        f.write("    client_name TEXT PRIMARY KEY,\n")
        f.write("    company TEXT,\n")
        f.write("    address TEXT,\n")
        f.write("    portal_token TEXT UNIQUE,\n")
        f.write("    portal_enabled BOOLEAN DEFAULT TRUE,\n")
        f.write("    archived BOOLEAN DEFAULT FALSE,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")
        
        # Engineers
        f.write("CREATE TABLE IF NOT EXISTS engineers (\n")
        f.write("    contact_name TEXT PRIMARY KEY,\n")
        f.write("    email TEXT,\n")
        f.write("    phone TEXT,\n")
        f.write("    address TEXT,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")
        
        # Site Contacts
        f.write("CREATE TABLE IF NOT EXISTS site_contacts (\n")
        f.write("    contact_name TEXT PRIMARY KEY,\n")
        f.write("    email TEXT,\n")
        f.write("    phone TEXT,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")

        # Brands
        f.write("CREATE TABLE IF NOT EXISTS brands (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    brand_name TEXT UNIQUE,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")

        # Client Sites
        f.write("CREATE TABLE IF NOT EXISTS client_sites (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    client_name TEXT REFERENCES clients(client_name),\n")
        f.write("    site_name TEXT NOT NULL,\n")
        f.write("    address TEXT,\n")
        f.write("    brand_name TEXT REFERENCES brands(brand_name),\n")
        f.write("    archived BOOLEAN DEFAULT FALSE,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")

        # Jobs
        f.write("CREATE TABLE IF NOT EXISTS jobs (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    job_number TEXT UNIQUE,\n")
        f.write("    date DATE NOT NULL,\n")
        f.write("    time TIME NOT NULL,\n")
        f.write("    brand TEXT,\n")
        f.write("    site_name TEXT,\n")
        f.write("    priority TEXT,\n")
        f.write("    status TEXT DEFAULT 'Scheduled',\n")
        f.write("    client_name TEXT REFERENCES clients(client_name),\n")
        f.write("    company TEXT,\n")
        f.write("    address TEXT,\n")
        f.write("    engineer_contact_name TEXT REFERENCES engineers(contact_name),\n")
        f.write("    engineer_email TEXT,\n")
        f.write("    engineer_phone TEXT,\n")
        f.write("    site_contact_name TEXT REFERENCES site_contacts(contact_name),\n")
        f.write("    site_contact_email TEXT,\n")
        f.write("    site_contact_phone TEXT,\n")
        f.write("    notes TEXT,\n")
        f.write("    photos TEXT,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")

        # Engineer Diary
        f.write("CREATE TABLE IF NOT EXISTS engineer_diary (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    engineer_name TEXT REFERENCES engineers(contact_name),\n")
        f.write("    date DATE NOT NULL,\n")
        f.write("    status TEXT,\n")
        f.write("    notes TEXT,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")

        # Password Resets (Basic)
        f.write("CREATE TABLE IF NOT EXISTS password_resets (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    email TEXT UNIQUE,\n")
        f.write("    token TEXT,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")
        
        # Extraction Reports
        f.write("CREATE TABLE IF NOT EXISTS extraction_reports (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    job_number TEXT,\n")
        f.write("    company TEXT,\n")
        f.write("    date DATE,\n")
        f.write("    time TIME,\n")
        f.write("    brand TEXT,\n")
        f.write("    address TEXT,\n")
        f.write("    contact_name TEXT,\n")
        f.write("    contact_number TEXT,\n")
        f.write("    status TEXT DEFAULT 'Draft',\n")
        f.write("    risk_pre INTEGER,\n")
        f.write("    risk_post INTEGER,\n")
        f.write("    remedial_requirements TEXT,\n")
        f.write("    risk_improvements TEXT,\n")
        f.write("    cleaning_interval_current TEXT,\n")
        f.write("    cleaning_interval_recommended TEXT,\n")
        f.write("    sketch_details TEXT,\n")
        f.write("    photos_taken TEXT,\n")
        f.write("    photos_path TEXT,\n")
        f.write("    client_signature TEXT,\n")
        f.write("    engineer_signature TEXT,\n")
        f.write("    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n")
        f.write(");\n\n")

        # Micron Readings
        f.write("CREATE TABLE IF NOT EXISTS extraction_micron_readings (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    report_id BIGINT REFERENCES extraction_reports(id),\n")
        f.write("    location TEXT,\n")
        f.write("    description TEXT,\n")
        f.write("    pre_clean INTEGER,\n")
        f.write("    post_clean INTEGER\n")
        f.write(");\n\n")

        # Photos
        f.write("CREATE TABLE IF NOT EXISTS extraction_photos (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    report_id BIGINT REFERENCES extraction_reports(id),\n")
        f.write("    photo_type TEXT,\n")
        f.write("    photo_path TEXT,\n")
        f.write("    caption TEXT,\n")
        f.write("    inspection_item TEXT\n")
        f.write(");\n\n")
        
        # Inspection Items
        f.write("CREATE TABLE IF NOT EXISTS extraction_inspection_items (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    report_id BIGINT REFERENCES extraction_reports(id),\n")
        f.write("    item_name TEXT,\n")
        f.write("    pre_clean TEXT,\n")
        f.write("    success BOOLEAN DEFAULT FALSE,\n")
        f.write("    pass_status BOOLEAN DEFAULT FALSE,\n")
        f.write("    fail_status BOOLEAN DEFAULT FALSE,\n")
        f.write("    advice TEXT,\n")
        f.write("    initial TEXT\n")
        f.write(");\n\n")

        # Filter Items
        f.write("CREATE TABLE IF NOT EXISTS extraction_filter_items (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    report_id BIGINT REFERENCES extraction_reports(id),\n")
        f.write("    filter_type TEXT,\n")
        f.write("    height INTEGER,\n")
        f.write("    width INTEGER,\n")
        f.write("    depth INTEGER,\n")
        f.write("    quantity INTEGER,\n")
        f.write("    pass_status BOOLEAN DEFAULT FALSE,\n")
        f.write("    fail_status BOOLEAN DEFAULT FALSE\n")
        f.write(");\n\n")

        f.write("-- 2. Data Insertion\n\n")
        
        with Session(source_engine) as session:
            for model in tables:
                table_name = model.__tablename__
                records = session.exec(select(model)).all()
                if not records:
                    continue
                    
                f.write(f"-- Data for {table_name}\n")
                
                for r in records:
                    data = r.model_dump()
                    
                    # Clean data for SQL
                    cols = []
                    vals = []
                    
                    for k, v in data.items():
                        if v is None:
                            continue
                        cols.append(k)
                        
                        if isinstance(v, (str, date, time, datetime)):
                            # Escape single quotes
                            v_str = str(v).replace("'", "''")
                            vals.append(f"'{v_str}'")
                        elif isinstance(v, bool):
                            vals.append("TRUE" if v else "FALSE")
                        else:
                            vals.append(str(v))
                            
                    if not cols:
                        continue
                        
                    col_str = ", ".join(cols)
                    val_str = ", ".join(vals)
                    
                    sql = f"INSERT INTO {table_name} ({col_str}) VALUES ({val_str}) ON CONFLICT DO NOTHING;\n"
                    f.write(sql)
                
                f.write("\n")

    print(f"Schema dump created at: {os.path.abspath(output_file)}")

if __name__ == "__main__":
    generate_dump()
