-- 1. Create the leave_requests table
CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engineer_name TEXT REFERENCES engineers(contact_name),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'Pending', -- 'Pending', 'Approved', 'Rejected'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add access_token column to engineers table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'engineers' AND column_name = 'access_token') THEN
        ALTER TABLE engineers ADD COLUMN access_token UUID DEFAULT gen_random_uuid();
        -- Ensure it's unique
        ALTER TABLE engineers ADD CONSTRAINT unique_access_token UNIQUE (access_token);
    END IF;
END $$;

-- 3. Populate existing engineers with a token if null (though default handles new ones)
UPDATE engineers SET access_token = gen_random_uuid() WHERE access_token IS NULL;
