
import uuid
from datetime import date as dt_date, time as dt_time, datetime
from typing import Optional, List
from pydantic import BaseModel, Field

CALL_OUT_MARKER = "[CALL OUT]"

# Note: In Supabase, ID generation and defaults are often handled by the database (Postgres).
# However, for Pydantic models used in FastAPI, we define what we expect to send/receive.

class Client(BaseModel):
    client_name: str
    company: Optional[str] = None
    address: Optional[str] = None
    portal_token: Optional[str] = None # Generated by DB or Logic
    portal_enabled: bool = True
    archived: bool = False
    created_at: Optional[datetime] = None

class Engineer(BaseModel):
    contact_name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    address: Optional[str] = None
    access_token: Optional[uuid.UUID] = None
    created_at: Optional[datetime] = None

class LeaveRequest(BaseModel):
    id: Optional[int] = None
    engineer_name: str
    start_date: dt_date
    end_date: dt_date
    reason: Optional[str] = None
    status: str = "Pending"
    created_at: Optional[datetime] = None

class SiteContact(BaseModel):
    contact_name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    created_at: Optional[datetime] = None

class Brand(BaseModel):
    id: Optional[int] = None
    brand_name: str
    created_at: Optional[datetime] = None

class ClientSite(BaseModel):
    id: Optional[int] = None
    client_name: str
    site_name: str
    address: Optional[str] = None
    postcode: Optional[str] = None
    brand_name: Optional[str] = None
    store_id_code: Optional[str] = None
    ac_number: Optional[str] = None
    frequency_number: Optional[int] = None
    last_clean: Optional[dt_date] = None
    archived: bool = False
    created_at: Optional[datetime] = None

class Job(BaseModel):
    id: Optional[int] = None
    job_number: str
    date: dt_date
    time: dt_time
    brand: Optional[str] = None
    site_name: Optional[str] = None
    priority: str
    status: str = "Scheduled"
    job_type: Optional[str] = "Extraction"
    client_name: str
    company: Optional[str] = None
    address: Optional[str] = None
    engineer_contact_name: Optional[str] = None
    engineer_email: Optional[str] = None
    engineer_phone: Optional[str] = None
    site_contact_name: Optional[str] = None
    site_contact_email: Optional[str] = None
    site_contact_phone: Optional[str] = None
    notes: Optional[str] = None
    photos: Optional[str] = None
    created_at: Optional[datetime] = None
    wa_link: Optional[str] = None # Runtime helper field

    def model_post_init(self, __context) -> None:
        if (self.job_type in (None, "", "Extraction")) and self.notes and self.notes.startswith(CALL_OUT_MARKER):
            self.job_type = "Breakdown/Callout"
            cleaned_notes = self.notes[len(CALL_OUT_MARKER):].lstrip(" -:\n")
            self.notes = cleaned_notes or None

class EngineerDiary(BaseModel):
    id: Optional[int] = None
    engineer_name: str
    date: dt_date
    status: str
    notes: Optional[str] = None
    created_at: Optional[datetime] = None

class User(BaseModel):
    id: Optional[int] = None
    username: str
    email: Optional[str] = None
    password: str
    role: str = "Admin"
    reset_token: Optional[str] = None
    reset_expires: Optional[datetime] = None
    created_at: Optional[datetime] = None

class PasswordReset(BaseModel):
    id: Optional[int] = None
    email: Optional[str] = None
    token: str
    created_at: Optional[datetime] = None

class ExtractionReport(BaseModel):
    id: Optional[int] = None
    job_number: Optional[str] = None
    company: Optional[str] = None
    date: Optional[dt_date] = None
    time: Optional[dt_time] = None # time object
    brand: Optional[str] = None
    address: Optional[str] = None
    contact_name: Optional[str] = None
    contact_number: Optional[str] = None
    job_type: Optional[str] = "Extraction"
    status: str = "Draft"
    risk_pre: Optional[int] = None
    risk_post: Optional[int] = None
    remedial_requirements: Optional[str] = None
    risk_improvements: Optional[str] = None
    cleaning_interval_current: Optional[str] = None
    cleaning_interval_recommended: Optional[str] = None
    sketch_details: Optional[str] = None
    issue_description: Optional[str] = None
    work_done: Optional[str] = None
    recommendations: Optional[str] = None
    sketch_photo_path: Optional[str] = None
    photos_taken: Optional[str] = None
    photos_path: Optional[str] = None
    client_signature: Optional[str] = None
    engineer_signature: Optional[str] = None
    created_at: Optional[datetime] = None

    def model_post_init(self, __context) -> None:
        if (self.job_type in (None, "", "Extraction")) and self.sketch_details and self.sketch_details.startswith(CALL_OUT_MARKER):
            self.job_type = "Breakdown/Callout"
            details = self.sketch_details[len(CALL_OUT_MARKER):].lstrip(" -:\n")
            if details.startswith("Work done:\n"):
                details = details[len("Work done:\n"):]
            if not self.work_done and details:
                self.work_done = details
        if self.job_type == "Breakdown/Callout":
            if not self.issue_description and self.remedial_requirements:
                self.issue_description = self.remedial_requirements
            if not self.recommendations and self.risk_improvements:
                self.recommendations = self.risk_improvements

class ExtractionMicronReading(BaseModel):
    id: Optional[int] = None
    report_id: int
    location: str
    description: Optional[str] = None
    pre_clean: Optional[int] = None
    post_clean: Optional[int] = None

class ExtractionPhoto(BaseModel):
    id: Optional[int] = None
    report_id: int
    photo_type: str
    photo_path: str
    caption: Optional[str] = None
    inspection_item: Optional[str] = None

class ExtractionInspectionItem(BaseModel):
    id: Optional[int] = None
    report_id: int
    item_name: str
    pre_clean: Optional[str] = None
    success: bool = False
    pass_status: bool = False
    fail_status: bool = False
    advice: Optional[str] = None
    initial: Optional[str] = None

class ExtractionFilterItem(BaseModel):
    id: Optional[int] = None
    report_id: int
    filter_type: str
    height: Optional[int] = None
    width: Optional[int] = None
    depth: Optional[int] = None
    quantity: Optional[int] = None
    pass_status: bool = False
    fail_status: bool = False

class SystemSetting(BaseModel):
    key: str
    value: str
